# Auto generate docs as a new commit for the docs repo
name: npm run docs

on:
  workflow_dispatch:
  push:
    branches:
       - main

permissions:
  contents: read

jobs:
  js-api-docs:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    # todo - run the npm install with a dockerfile setup instead of pure
    # install but not important to do right now since install isnt too long

    # NOTE - 
    #
    # For local documentation or to check the local output when writing your own pr to see how it will
    # update, run `npm run docs`. As a heads up, order of creation of docs depends on your operating
    # system, so if when you run this the order looks different, no worries - in the repo itself our
    # action will handle that for you and default to use the right version for these automatically
    # generated docs.
    # 
    # We're using mac as default for doc order generation (the order from that os makes the most sense
    # from a readability perspective).
    
    - uses: actions/setup-node@v4
      with:
        node-version: 21

    - name: Install Dependencies
      run: |
        npm install

    - name: 👷 Write the markdown docs
      run: |
        npm run docs

    - name: read the doc file
      run: |
        head -n 12 "./docs/js-api.md"

    - name: Get Docs content
      id: get-docs
      run: |
        rm -rf ../doc
        mkdir -p ../doc
        cp -rf ./docs/* ../doc/

    - name: see if info is there
      run: |
        echo "ll .."
        ls -al ..
        echo "ll ."
        ls -al .

    - name: Checkout documentation Repository
      uses: actions/checkout@v4
      with:
        repository: Volumetrics-io/documentation
        ref: main
        token: ${{ secrets.MRJS_AND_DOCS_REPO_PAT }}

    - name: Update Docs
      run: |
        rm "./source/pages/02Javascript API.md"
        mv -f "../doc/js-api.md" "./source/pages/02Javascript API.md"

    - name: cat for debug
      run: |
        cat "./source/pages/02Javascript API.md"

    # - name: Commit only if there are changes
    #   run: |
    #     if [[ -n $(git diff --exit-code) ]]; then
    #       echo "Changes detected. Committing and pushing."
    #       git config user.name 'github-actions[bot]'
    #       git config user.email 'github-actions[bot]@users.noreply.github.com'
    #       commit_message=$'👷 MR.js - Auto Generated Docs 👷\n\nChanges at '"${GITHUB_SHA}"
    #       git add .
    #       git commit -m "$commit_message"
    #       git push --quiet --set-upstream origin HEAD
    #     else
    #       echo "No changes detected. Exiting without committing."
    #     fi
    #   env:
    #       GITHUB_TOKEN: ${{ secrets.MRJS_AND_DOCS_REPO_PAT }}

