# Auto generate docs as a new commit for the docs repo
name: npm run docs

on:
  workflow_dispatch:
  push:

permissions:
  contents: read

jobs:
  docs:
    runs-on: ubuntu-latest
    
    - name: Checkout Current Repository
      uses: actions/checkout@v3
    
    # todo - run the npm install with a dockerfile setup instead of pure
    # install but not important to do right now since install isnt too long
    
    - uses: actions/setup-node@v3
      with:
        node-version: 21

    - name: Configure Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Install Dependencies
      run: |
        npm install

    - name: 👷 Write the html docs
      run: |
        npm run docs

    - name: Get Docs content
        id: get-docs
        run: |
          cp -rf docs/* > ../docs

    - name: see if info is there
      run: |
        echo "ll .."
        ls -al ..
        echo "ll ."
        ls -al .

    - name: Checkout docs Repository
      uses: actions/checkout@v3
      with:
        repository: Volumetrics-io/docs
        token: ${{ secrets.PAT }}
        ref: main

    - name: Update Docs
      run: |
        cp -rf ../docs ./auto
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add auto/*
        git commit -m "👷 MR.js - Auto Generated Docs 👷" 
        git push --quiet --set-upstream origin HEAD
      #env:
        #PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

