# Check MRjs has been linted
name: npm run check-format
on:
  workflow_dispatch:
  push:

permissions:
  contents: read

jobs:
  check-format:
    runs-on: ubuntu-latest
    # needs: build # todo
    steps:
    - uses: actions/checkout@v2
    
      # todo - run the npm install with a dockerfile setup instead of pure
      # install but not important to do right now since install isnt too long
    
    - uses: actions/setup-node@v2
      with:
        node-version: 18

    # todo - are the dependencies needed for lint?
    
    - name: Install Dependencies
      run: |
        npm install
    
    - name: 👷 Check if format is needed
      run: |
        if ! npm run check-format; then
          echo "Some files need formatting. Run 'npm run format' to format them."
          exit 1
        fi
