# Check MRjs has been linted
name: npm run format

on:
  workflow_dispatch:
  push:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    # needs: build # todo
    steps:
    - uses: actions/checkout@v2
    
      # todo - run the npm install with a dockerfile setup instead of pure
      # install but not important to do right now since install isnt too long
    
    - uses: actions/setup-node@v2
      with:
        node-version: 18

    # todo - are the dependencies needed for lint?
    
    - name: Install Dependencies
      run: |
        npm install
    
    - name: 👷 Format
      run: npm run format

    - name: Error if there are changed files
      run: |
        # Get the list of changed files
        changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})

        # Print the changed files
        echo "Changed files:"
        echo "$changed_files"

        # Check if there are any changed files
        if [ -n "$changed_files" ]; then
          echo "There are changed files. Perform your actions here."
        else
          echo "No changed files. Skip further actions."
        fi

