# Test MRjs and confirm everything passes
name: npm test

on:
  workflow_dispatch:
  push:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    needs: build 
    steps:
    - uses: actions/checkout@v4
    
      # todo - run the npm install with a dockerfile setup instead of pure
      # install but not important to do right now since install isnt too long
    
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    
    - name: Install Dependencies
      run: |
        npm install

        #- name: 👷 Test
        #run: |
        #  npm run build
